{
 "cells": [
  {
   "cell_type": "markdown",
   "source": [
    "## How can I use python in the solidworks api?"
   ],
   "metadata": {
    "collapsed": false
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "Using Python in the SolidWorks API (Application Programming Interface) allows you to automate tasks and interact with SolidWorks, a popular computer-aided design (CAD) software. Here's a general outline of the steps you can follow to use Python in the SolidWorks API:\n",
    "\n",
    "Install SolidWorks: To use the SolidWorks API, you'll need to have SolidWorks software installed on your computer. Make sure you have a valid license and the appropriate version of SolidWorks that supports API access.\n",
    "\n",
    "Install the SolidWorks API Library: SolidWorks provides a Python library called \"sw-comtypes\" that allows you to interact with the SolidWorks API. You can install it using the Python package manager, such as pip, by running the following command in your Python environment:"
   ],
   "metadata": {
    "collapsed": false
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "!pip install sw-comtypes"
   ],
   "metadata": {
    "collapsed": false
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "Import the SolidWorks API library: In your Python script, you need to import the SolidWorks API library using the comtypes module. Here's an example:"
   ],
   "metadata": {
    "collapsed": false
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "import comtypes.client as sw"
   ],
   "metadata": {
    "collapsed": false
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "Connect to SolidWorks: You need to create a connection to SolidWorks using the sw.GetActiveObject function, which returns an instance of the SolidWorks API object. Here's an example:"
   ],
   "metadata": {
    "collapsed": false
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "# Connect to SolidWorks\n",
    "swApp = sw.GetActiveObject(\"SldWorks.Application\")"
   ],
   "metadata": {
    "collapsed": false
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "Access SolidWorks API Objects and Methods: Once you have a connection to SolidWorks, you can use the available objects and methods in the SolidWorks API to automate tasks. For example, you can create, modify, and save SolidWorks documents, create sketches, features, and assemblies, and manipulate their properties. Here's an example that creates a new part document in SolidWorks:"
   ],
   "metadata": {
    "collapsed": false
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "# Create a new part document\n",
    "part = swApp.NewDocument(sw.constants.swDocPART)"
   ],
   "metadata": {
    "collapsed": false
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "Run your Python script: You can run your Python script from an external Python environment or directly from the SolidWorks Integrated Development Environment (IDE) using the SolidWorks macro feature.\n",
    "Note: It's important to thoroughly review the SolidWorks API documentation, including the object model and available methods, to understand how to use the API effectively and safely.\n",
    "\n",
    "Caution: Be careful when automating tasks with the SolidWorks API, as it can potentially modify your SolidWorks files. Always backup your files and test your scripts in a safe environment to avoid any unintentional changes to your SolidWorks documents."
   ],
   "metadata": {
    "collapsed": false
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "Erick Rodriguez Martinez\n",
    "## could you show me and example to create a new tab ?\n",
    "\n",
    "Sure! Here's an example of how you can create a new tab in the SolidWorks FeatureManager design tree using the SolidWorks API in Python:"
   ],
   "metadata": {
    "collapsed": false
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "import comtypes.client as sw\n",
    "\n",
    "# Connect to SolidWorks\n",
    "swApp = sw.GetActiveObject(\"SldWorks.Application\")\n",
    "\n",
    "# Get the active document\n",
    "doc = swApp.ActiveDoc\n",
    "\n",
    "# Access the FeatureManager design tree\n",
    "featMgr = doc.FeatureManager\n",
    "\n",
    "# Create a new tab\n",
    "tabName = \"MyCustomTab\"  # specify the name of the new tab\n",
    "tab = featMgr.InsertFeatureTreeFolder2(0, tabName, 1)\n",
    "\n",
    "# Check if tab creation was successful\n",
    "if tab is not None:\n",
    "    print(f\"New tab '{tabName}' created successfully.\")\n",
    "else:\n",
    "    print(\"Failed to create new tab.\")"
   ],
   "metadata": {
    "collapsed": false
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "In this example, we first connect to SolidWorks using the sw.GetActiveObject function to get the active SolidWorks application object. Then, we access the FeatureManager design tree of the active document using the doc.FeatureManager property.\n",
    "\n",
    "Next, we use the InsertFeatureTreeFolder2 method of the FeatureManager object to create a new tab in the design tree. The method takes three arguments: the index where the new tab should be inserted (0 for the first position), the name of the new tab, and the type of the tab (1 for a standard tab).\n",
    "\n",
    "Finally, we check if the tab creation was successful by verifying if the returned tab object is not None, and print a message accordingly.\n",
    "\n",
    "Note: This is a basic example and there are many other options and methods available in the SolidWorks API for customizing the tab appearance, adding features to the tab, and more. Make sure to refer to the SolidWorks API documentation for further details and customization options.\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "Erick Rodriguez Martinez\n",
    "## I mean a tab in the ribbon\n",
    "I apologize for the confusion. Creating a new tab in the ribbon in SolidWorks using the SolidWorks API requires a more involved process. Here's an example:"
   ],
   "metadata": {
    "collapsed": false
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "import comtypes.client as sw\n",
    "\n",
    "# Connect to SolidWorks\n",
    "swApp = sw.GetActiveObject(\"SldWorks.Application\")\n",
    "\n",
    "# Get the command manager\n",
    "cmdMgr = swApp.GetCommandManager()\n",
    "\n",
    "# Create a new tab\n",
    "tabName = \"MyCustomTab\"  # specify the name of the new tab\n",
    "tabId = cmdMgr.AddTab(tabName, 0)\n",
    "\n",
    "# Add a button to the new tab\n",
    "cmdId = cmdMgr.AddCommandItem(tabId, 0, \"MyCustomButton\", sw.constants.swCommandItemType_e.swMenuItem, \"My Custom Button\", \"My custom button tooltip\", \"C:\\\\path\\\\to\\\\my_icon.bmp\")\n",
    "\n",
    "# Define a callback function for the button\n",
    "def onButtonClick():\n",
    "    print(\"Custom button clicked!\")\n",
    "\n",
    "# Add the callback function to the button\n",
    "cmdMgr.AddCallback(cmdId, sw.constants.swCommandItemType_e.swMenuItem, onButtonClick)"
   ],
   "metadata": {
    "collapsed": false
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "\n",
    "In this example, we first connect to SolidWorks using the sw.GetActiveObject function to get the active SolidWorks application object. Then, we access the command manager using the swApp.GetCommandManager() method.\n",
    "\n",
    "Next, we use the AddTab method of the command manager to create a new tab in the ribbon. The method takes two arguments: the name of the new tab, and the index where the new tab should be inserted (0 for the first position). The method returns a tab ID that can be used to add items to the tab.\n",
    "\n",
    "Then, we use the AddCommandItem method of the command manager to add a button to the new tab. The method takes six arguments: the tab ID, the index where the new button should be inserted (0 for the first position), a unique command ID for the button, the type of the button (in this case, a menu item), the display text for the button, the tooltip for the button, and the file path to an icon for the button.\n",
    "\n",
    "Finally, we define a callback function (onButtonClick in this example) that will be executed when the button is clicked, and use the AddCallback method of the command manager to add the callback function to the button. The method takes three arguments: the command ID of the button, the type of the button (in this case, a menu item), and the callback function.\n",
    "\n",
    "Note: This is a simplified example and there are many other options and methods available in the SolidWorks API for customizing the ribbon tab appearance, adding different types of controls (such as dropdowns or checkboxes), handling events, and more. Make sure to refer to the SolidWorks API documentation for further details and customization options.\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "Erick Rodriguez Martinez\n",
    "## could you generate a pdf for all we were talking incluiding a chart with the most common comands and functions of the API?\n",
    "I apologize, but as a text-based language model, I am not able to generate PDFs or other graphical representations. However, I can provide you with a list of some common commands and functions in the SolidWorks API that you can use as a reference:\n",
    "\n",
    "GetActiveObject: Connects to the active instance of SolidWorks.\n",
    "ActiveDoc: Returns the active document in SolidWorks.\n",
    "FeatureManager: Represents the FeatureManager design tree in SolidWorks and provides methods for manipulating features and components.\n",
    "InsertFeatureTreeFolder2: Inserts a new tab in the FeatureManager design tree.\n",
    "AddTab: Adds a new tab in the SolidWorks ribbon.\n",
    "AddCommandItem: Adds a new command item (e.g., button) to a ribbon tab.\n",
    "AddCallback: Adds a callback function to a command item to handle events.\n",
    "GetCustomInfo: Retrieves custom information (metadata) associated with a document or a feature.\n",
    "GetSelectionSet: Retrieves the currently selected entities (e.g., features, components) in SolidWorks.\n",
    "ISldWorks: Represents the SolidWorks application instance and provides methods for controlling SolidWorks settings and options.\n",
    "These are just a few examples of the many commands and functions available in the SolidWorks API. The SolidWorks API documentation is a comprehensive resource that provides detailed information about all the available commands and functions, along with their parameters and usage. You can refer to the SolidWorks API documentation for a more complete list of commands and functions, as well as examples and tutorials on how to use them in your Python scripts."
   ],
   "metadata": {
    "collapsed": false
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [],
   "metadata": {
    "collapsed": false
   }
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
